// Code generated by go-swagger; DO NOT EDIT.

package matcher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewMatcherResumeParams creates a new MatcherResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMatcherResumeParams() *MatcherResumeParams {
	return &MatcherResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMatcherResumeParamsWithTimeout creates a new MatcherResumeParams object
// with the ability to set a timeout on a request.
func NewMatcherResumeParamsWithTimeout(timeout time.Duration) *MatcherResumeParams {
	return &MatcherResumeParams{
		timeout: timeout,
	}
}

// NewMatcherResumeParamsWithContext creates a new MatcherResumeParams object
// with the ability to set a context for a request.
func NewMatcherResumeParamsWithContext(ctx context.Context) *MatcherResumeParams {
	return &MatcherResumeParams{
		Context: ctx,
	}
}

// NewMatcherResumeParamsWithHTTPClient creates a new MatcherResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewMatcherResumeParamsWithHTTPClient(client *http.Client) *MatcherResumeParams {
	return &MatcherResumeParams{
		HTTPClient: client,
	}
}

/* MatcherResumeParams contains all the parameters to send to the API endpoint
   for the matcher resume operation.

   Typically these are written to a http.Request.
*/
type MatcherResumeParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// Request.
	Request *go_sovren_models.SovrenMatchResumeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the matcher resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MatcherResumeParams) WithDefaults() *MatcherResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the matcher resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MatcherResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the matcher resume params
func (o *MatcherResumeParams) WithTimeout(timeout time.Duration) *MatcherResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the matcher resume params
func (o *MatcherResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the matcher resume params
func (o *MatcherResumeParams) WithContext(ctx context.Context) *MatcherResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the matcher resume params
func (o *MatcherResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the matcher resume params
func (o *MatcherResumeParams) WithHTTPClient(client *http.Client) *MatcherResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the matcher resume params
func (o *MatcherResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the matcher resume params
func (o *MatcherResumeParams) WithSovrenAccountID(sovrenAccountID string) *MatcherResumeParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the matcher resume params
func (o *MatcherResumeParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the matcher resume params
func (o *MatcherResumeParams) WithSovrenServiceKey(sovrenServiceKey string) *MatcherResumeParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the matcher resume params
func (o *MatcherResumeParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithRequest adds the request to the matcher resume params
func (o *MatcherResumeParams) WithRequest(request *go_sovren_models.SovrenMatchResumeRequest) *MatcherResumeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the matcher resume params
func (o *MatcherResumeParams) SetRequest(request *go_sovren_models.SovrenMatchResumeRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MatcherResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
