// Code generated by go-swagger; DO NOT EDIT.

package index

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewIndexPostParams creates a new IndexPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIndexPostParams() *IndexPostParams {
	return &IndexPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIndexPostParamsWithTimeout creates a new IndexPostParams object
// with the ability to set a timeout on a request.
func NewIndexPostParamsWithTimeout(timeout time.Duration) *IndexPostParams {
	return &IndexPostParams{
		timeout: timeout,
	}
}

// NewIndexPostParamsWithContext creates a new IndexPostParams object
// with the ability to set a context for a request.
func NewIndexPostParamsWithContext(ctx context.Context) *IndexPostParams {
	return &IndexPostParams{
		Context: ctx,
	}
}

// NewIndexPostParamsWithHTTPClient creates a new IndexPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewIndexPostParamsWithHTTPClient(client *http.Client) *IndexPostParams {
	return &IndexPostParams{
		HTTPClient: client,
	}
}

/* IndexPostParams contains all the parameters to send to the API endpoint
   for the index post operation.

   Typically these are written to a http.Request.
*/
type IndexPostParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// IndexID.
	IndexID string

	// Request.
	Request *go_sovren_models.SovrenSaasDomainCreateIndexRequestModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the index post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexPostParams) WithDefaults() *IndexPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the index post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the index post params
func (o *IndexPostParams) WithTimeout(timeout time.Duration) *IndexPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the index post params
func (o *IndexPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the index post params
func (o *IndexPostParams) WithContext(ctx context.Context) *IndexPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the index post params
func (o *IndexPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the index post params
func (o *IndexPostParams) WithHTTPClient(client *http.Client) *IndexPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the index post params
func (o *IndexPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the index post params
func (o *IndexPostParams) WithSovrenAccountID(sovrenAccountID string) *IndexPostParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the index post params
func (o *IndexPostParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the index post params
func (o *IndexPostParams) WithSovrenServiceKey(sovrenServiceKey string) *IndexPostParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the index post params
func (o *IndexPostParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithIndexID adds the indexID to the index post params
func (o *IndexPostParams) WithIndexID(indexID string) *IndexPostParams {
	o.SetIndexID(indexID)
	return o
}

// SetIndexID adds the indexId to the index post params
func (o *IndexPostParams) SetIndexID(indexID string) {
	o.IndexID = indexID
}

// WithRequest adds the request to the index post params
func (o *IndexPostParams) WithRequest(request *go_sovren_models.SovrenSaasDomainCreateIndexRequestModel) *IndexPostParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the index post params
func (o *IndexPostParams) SetRequest(request *go_sovren_models.SovrenSaasDomainCreateIndexRequestModel) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *IndexPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param indexId
	if err := r.SetPathParam("indexId", o.IndexID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
