// Code generated by go-swagger; DO NOT EDIT.

package index

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIndexGet0Params creates a new IndexGet0Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIndexGet0Params() *IndexGet0Params {
	return &IndexGet0Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewIndexGet0ParamsWithTimeout creates a new IndexGet0Params object
// with the ability to set a timeout on a request.
func NewIndexGet0ParamsWithTimeout(timeout time.Duration) *IndexGet0Params {
	return &IndexGet0Params{
		timeout: timeout,
	}
}

// NewIndexGet0ParamsWithContext creates a new IndexGet0Params object
// with the ability to set a context for a request.
func NewIndexGet0ParamsWithContext(ctx context.Context) *IndexGet0Params {
	return &IndexGet0Params{
		Context: ctx,
	}
}

// NewIndexGet0ParamsWithHTTPClient creates a new IndexGet0Params object
// with the ability to set a custom HTTPClient for a request.
func NewIndexGet0ParamsWithHTTPClient(client *http.Client) *IndexGet0Params {
	return &IndexGet0Params{
		HTTPClient: client,
	}
}

/* IndexGet0Params contains all the parameters to send to the API endpoint
   for the index get 0 operation.

   Typically these are written to a http.Request.
*/
type IndexGet0Params struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the index get 0 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexGet0Params) WithDefaults() *IndexGet0Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the index get 0 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexGet0Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the index get 0 params
func (o *IndexGet0Params) WithTimeout(timeout time.Duration) *IndexGet0Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the index get 0 params
func (o *IndexGet0Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the index get 0 params
func (o *IndexGet0Params) WithContext(ctx context.Context) *IndexGet0Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the index get 0 params
func (o *IndexGet0Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the index get 0 params
func (o *IndexGet0Params) WithHTTPClient(client *http.Client) *IndexGet0Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the index get 0 params
func (o *IndexGet0Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the index get 0 params
func (o *IndexGet0Params) WithSovrenAccountID(sovrenAccountID string) *IndexGet0Params {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the index get 0 params
func (o *IndexGet0Params) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the index get 0 params
func (o *IndexGet0Params) WithSovrenServiceKey(sovrenServiceKey string) *IndexGet0Params {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the index get 0 params
func (o *IndexGet0Params) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WriteToRequest writes these params to a swagger request
func (o *IndexGet0Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
