// Code generated by go-swagger; DO NOT EDIT.

package index

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIndexGetIndexDocumentCountParams creates a new IndexGetIndexDocumentCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIndexGetIndexDocumentCountParams() *IndexGetIndexDocumentCountParams {
	return &IndexGetIndexDocumentCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIndexGetIndexDocumentCountParamsWithTimeout creates a new IndexGetIndexDocumentCountParams object
// with the ability to set a timeout on a request.
func NewIndexGetIndexDocumentCountParamsWithTimeout(timeout time.Duration) *IndexGetIndexDocumentCountParams {
	return &IndexGetIndexDocumentCountParams{
		timeout: timeout,
	}
}

// NewIndexGetIndexDocumentCountParamsWithContext creates a new IndexGetIndexDocumentCountParams object
// with the ability to set a context for a request.
func NewIndexGetIndexDocumentCountParamsWithContext(ctx context.Context) *IndexGetIndexDocumentCountParams {
	return &IndexGetIndexDocumentCountParams{
		Context: ctx,
	}
}

// NewIndexGetIndexDocumentCountParamsWithHTTPClient creates a new IndexGetIndexDocumentCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewIndexGetIndexDocumentCountParamsWithHTTPClient(client *http.Client) *IndexGetIndexDocumentCountParams {
	return &IndexGetIndexDocumentCountParams{
		HTTPClient: client,
	}
}

/* IndexGetIndexDocumentCountParams contains all the parameters to send to the API endpoint
   for the index get index document count operation.

   Typically these are written to a http.Request.
*/
type IndexGetIndexDocumentCountParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// IndexID.
	IndexID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the index get index document count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexGetIndexDocumentCountParams) WithDefaults() *IndexGetIndexDocumentCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the index get index document count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexGetIndexDocumentCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) WithTimeout(timeout time.Duration) *IndexGetIndexDocumentCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) WithContext(ctx context.Context) *IndexGetIndexDocumentCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) WithHTTPClient(client *http.Client) *IndexGetIndexDocumentCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) WithSovrenAccountID(sovrenAccountID string) *IndexGetIndexDocumentCountParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) WithSovrenServiceKey(sovrenServiceKey string) *IndexGetIndexDocumentCountParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithIndexID adds the indexID to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) WithIndexID(indexID string) *IndexGetIndexDocumentCountParams {
	o.SetIndexID(indexID)
	return o
}

// SetIndexID adds the indexId to the index get index document count params
func (o *IndexGetIndexDocumentCountParams) SetIndexID(indexID string) {
	o.IndexID = indexID
}

// WriteToRequest writes these params to a swagger request
func (o *IndexGetIndexDocumentCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param indexId
	if err := r.SetPathParam("indexId", o.IndexID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
