// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNormalizationsDeleteParams creates a new NormalizationsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNormalizationsDeleteParams() *NormalizationsDeleteParams {
	return &NormalizationsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNormalizationsDeleteParamsWithTimeout creates a new NormalizationsDeleteParams object
// with the ability to set a timeout on a request.
func NewNormalizationsDeleteParamsWithTimeout(timeout time.Duration) *NormalizationsDeleteParams {
	return &NormalizationsDeleteParams{
		timeout: timeout,
	}
}

// NewNormalizationsDeleteParamsWithContext creates a new NormalizationsDeleteParams object
// with the ability to set a context for a request.
func NewNormalizationsDeleteParamsWithContext(ctx context.Context) *NormalizationsDeleteParams {
	return &NormalizationsDeleteParams{
		Context: ctx,
	}
}

// NewNormalizationsDeleteParamsWithHTTPClient creates a new NormalizationsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewNormalizationsDeleteParamsWithHTTPClient(client *http.Client) *NormalizationsDeleteParams {
	return &NormalizationsDeleteParams{
		HTTPClient: client,
	}
}

/* NormalizationsDeleteParams contains all the parameters to send to the API endpoint
   for the normalizations delete operation.

   Typically these are written to a http.Request.
*/
type NormalizationsDeleteParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// Key.
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the normalizations delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsDeleteParams) WithDefaults() *NormalizationsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the normalizations delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the normalizations delete params
func (o *NormalizationsDeleteParams) WithTimeout(timeout time.Duration) *NormalizationsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the normalizations delete params
func (o *NormalizationsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the normalizations delete params
func (o *NormalizationsDeleteParams) WithContext(ctx context.Context) *NormalizationsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the normalizations delete params
func (o *NormalizationsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the normalizations delete params
func (o *NormalizationsDeleteParams) WithHTTPClient(client *http.Client) *NormalizationsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the normalizations delete params
func (o *NormalizationsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the normalizations delete params
func (o *NormalizationsDeleteParams) WithSovrenAccountID(sovrenAccountID string) *NormalizationsDeleteParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the normalizations delete params
func (o *NormalizationsDeleteParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the normalizations delete params
func (o *NormalizationsDeleteParams) WithSovrenServiceKey(sovrenServiceKey string) *NormalizationsDeleteParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the normalizations delete params
func (o *NormalizationsDeleteParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithKey adds the key to the normalizations delete params
func (o *NormalizationsDeleteParams) WithKey(key string) *NormalizationsDeleteParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the normalizations delete params
func (o *NormalizationsDeleteParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *NormalizationsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
