// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NormalizationsGet0Reader is a Reader for the NormalizationsGet0 structure.
type NormalizationsGet0Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NormalizationsGet0Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNormalizationsGet0OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewNormalizationsGet0Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNormalizationsGet0OK creates a NormalizationsGet0OK with default headers values
func NewNormalizationsGet0OK() *NormalizationsGet0OK {
	return &NormalizationsGet0OK{}
}

/* NormalizationsGet0OK describes a response with status code 200, with default header values.

The byte array representing the zip file
*/
type NormalizationsGet0OK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SystemByteMscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089
}

func (o *NormalizationsGet0OK) Error() string {
	return fmt.Sprintf("[GET /v10/normalizations/{key}][%d] normalizationsGet0OK  %+v", 200, o.Payload)
}
func (o *NormalizationsGet0OK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SystemByteMscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089 {
	return o.Payload
}

func (o *NormalizationsGet0OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SystemByteMscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNormalizationsGet0Unauthorized creates a NormalizationsGet0Unauthorized with default headers values
func NewNormalizationsGet0Unauthorized() *NormalizationsGet0Unauthorized {
	return &NormalizationsGet0Unauthorized{}
}

/* NormalizationsGet0Unauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type NormalizationsGet0Unauthorized struct {
	Payload string
}

func (o *NormalizationsGet0Unauthorized) Error() string {
	return fmt.Sprintf("[GET /v10/normalizations/{key}][%d] normalizationsGet0Unauthorized  %+v", 401, o.Payload)
}
func (o *NormalizationsGet0Unauthorized) GetPayload() string {
	return o.Payload
}

func (o *NormalizationsGet0Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
