// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NormalizationsGetReader is a Reader for the NormalizationsGet structure.
type NormalizationsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NormalizationsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNormalizationsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewNormalizationsGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNormalizationsGetOK creates a NormalizationsGetOK with default headers values
func NewNormalizationsGetOK() *NormalizationsGetOK {
	return &NormalizationsGetOK{}
}

/* NormalizationsGetOK describes a response with status code 200, with default header values.

A collection of available Normalizations
*/
type NormalizationsGetOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *NormalizationsGetOK) Error() string {
	return fmt.Sprintf("[GET /v10/normalizations][%d] normalizationsGetOK  %+v", 200, o.Payload)
}
func (o *NormalizationsGetOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *NormalizationsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNormalizationsGetUnauthorized creates a NormalizationsGetUnauthorized with default headers values
func NewNormalizationsGetUnauthorized() *NormalizationsGetUnauthorized {
	return &NormalizationsGetUnauthorized{}
}

/* NormalizationsGetUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type NormalizationsGetUnauthorized struct {
	Payload string
}

func (o *NormalizationsGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v10/normalizations][%d] normalizationsGetUnauthorized  %+v", 401, o.Payload)
}
func (o *NormalizationsGetUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *NormalizationsGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
