// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewNormalizationsPostParams creates a new NormalizationsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNormalizationsPostParams() *NormalizationsPostParams {
	return &NormalizationsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNormalizationsPostParamsWithTimeout creates a new NormalizationsPostParams object
// with the ability to set a timeout on a request.
func NewNormalizationsPostParamsWithTimeout(timeout time.Duration) *NormalizationsPostParams {
	return &NormalizationsPostParams{
		timeout: timeout,
	}
}

// NewNormalizationsPostParamsWithContext creates a new NormalizationsPostParams object
// with the ability to set a context for a request.
func NewNormalizationsPostParamsWithContext(ctx context.Context) *NormalizationsPostParams {
	return &NormalizationsPostParams{
		Context: ctx,
	}
}

// NewNormalizationsPostParamsWithHTTPClient creates a new NormalizationsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewNormalizationsPostParamsWithHTTPClient(client *http.Client) *NormalizationsPostParams {
	return &NormalizationsPostParams{
		HTTPClient: client,
	}
}

/* NormalizationsPostParams contains all the parameters to send to the API endpoint
   for the normalizations post operation.

   Typically these are written to a http.Request.
*/
type NormalizationsPostParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	/* Request.

	   The CreateNormalizationRequest object.
	*/
	Request *go_sovren_models.SovrenSaasDomainCreateNormalizationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the normalizations post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsPostParams) WithDefaults() *NormalizationsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the normalizations post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the normalizations post params
func (o *NormalizationsPostParams) WithTimeout(timeout time.Duration) *NormalizationsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the normalizations post params
func (o *NormalizationsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the normalizations post params
func (o *NormalizationsPostParams) WithContext(ctx context.Context) *NormalizationsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the normalizations post params
func (o *NormalizationsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the normalizations post params
func (o *NormalizationsPostParams) WithHTTPClient(client *http.Client) *NormalizationsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the normalizations post params
func (o *NormalizationsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the normalizations post params
func (o *NormalizationsPostParams) WithSovrenAccountID(sovrenAccountID string) *NormalizationsPostParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the normalizations post params
func (o *NormalizationsPostParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the normalizations post params
func (o *NormalizationsPostParams) WithSovrenServiceKey(sovrenServiceKey string) *NormalizationsPostParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the normalizations post params
func (o *NormalizationsPostParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithRequest adds the request to the normalizations post params
func (o *NormalizationsPostParams) WithRequest(request *go_sovren_models.SovrenSaasDomainCreateNormalizationRequest) *NormalizationsPostParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the normalizations post params
func (o *NormalizationsPostParams) SetRequest(request *go_sovren_models.SovrenSaasDomainCreateNormalizationRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *NormalizationsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
