// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NormalizationsPutReader is a Reader for the NormalizationsPut structure.
type NormalizationsPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NormalizationsPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNormalizationsPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNormalizationsPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNormalizationsPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNormalizationsPutOK creates a NormalizationsPutOK with default headers values
func NewNormalizationsPutOK() *NormalizationsPutOK {
	return &NormalizationsPutOK{}
}

/* NormalizationsPutOK describes a response with status code 200, with default header values.

A model describing the Normalization PUT
*/
type NormalizationsPutOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *NormalizationsPutOK) Error() string {
	return fmt.Sprintf("[PUT /v10/normalizations/{key}][%d] normalizationsPutOK  %+v", 200, o.Payload)
}
func (o *NormalizationsPutOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *NormalizationsPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNormalizationsPutBadRequest creates a NormalizationsPutBadRequest with default headers values
func NewNormalizationsPutBadRequest() *NormalizationsPutBadRequest {
	return &NormalizationsPutBadRequest{}
}

/* NormalizationsPutBadRequest describes a response with status code 400, with default header values.

A message describing why the message was in a bad state.
*/
type NormalizationsPutBadRequest struct {
	Payload string
}

func (o *NormalizationsPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v10/normalizations/{key}][%d] normalizationsPutBadRequest  %+v", 400, o.Payload)
}
func (o *NormalizationsPutBadRequest) GetPayload() string {
	return o.Payload
}

func (o *NormalizationsPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNormalizationsPutUnauthorized creates a NormalizationsPutUnauthorized with default headers values
func NewNormalizationsPutUnauthorized() *NormalizationsPutUnauthorized {
	return &NormalizationsPutUnauthorized{}
}

/* NormalizationsPutUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type NormalizationsPutUnauthorized struct {
	Payload string
}

func (o *NormalizationsPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v10/normalizations/{key}][%d] normalizationsPutUnauthorized  %+v", 401, o.Payload)
}
func (o *NormalizationsPutUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *NormalizationsPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
