// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NormalizationsDeleteReader is a Reader for the NormalizationsDelete structure.
type NormalizationsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NormalizationsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNormalizationsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNormalizationsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNormalizationsDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNormalizationsDeleteOK creates a NormalizationsDeleteOK with default headers values
func NewNormalizationsDeleteOK() *NormalizationsDeleteOK {
	return &NormalizationsDeleteOK{}
}

/* NormalizationsDeleteOK describes a response with status code 200, with default header values.

An empty model
*/
type NormalizationsDeleteOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *NormalizationsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /v10/normalizations/{key}][%d] normalizationsDeleteOK  %+v", 200, o.Payload)
}
func (o *NormalizationsDeleteOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *NormalizationsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainNormalizationResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNormalizationsDeleteBadRequest creates a NormalizationsDeleteBadRequest with default headers values
func NewNormalizationsDeleteBadRequest() *NormalizationsDeleteBadRequest {
	return &NormalizationsDeleteBadRequest{}
}

/* NormalizationsDeleteBadRequest describes a response with status code 400, with default header values.

A message describing why the message was in a bad state.
*/
type NormalizationsDeleteBadRequest struct {
	Payload string
}

func (o *NormalizationsDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v10/normalizations/{key}][%d] normalizationsDeleteBadRequest  %+v", 400, o.Payload)
}
func (o *NormalizationsDeleteBadRequest) GetPayload() string {
	return o.Payload
}

func (o *NormalizationsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNormalizationsDeleteUnauthorized creates a NormalizationsDeleteUnauthorized with default headers values
func NewNormalizationsDeleteUnauthorized() *NormalizationsDeleteUnauthorized {
	return &NormalizationsDeleteUnauthorized{}
}

/* NormalizationsDeleteUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type NormalizationsDeleteUnauthorized struct {
	Payload string
}

func (o *NormalizationsDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v10/normalizations/{key}][%d] normalizationsDeleteUnauthorized  %+v", 401, o.Payload)
}
func (o *NormalizationsDeleteUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *NormalizationsDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
