// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNormalizationsGet0Params creates a new NormalizationsGet0Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNormalizationsGet0Params() *NormalizationsGet0Params {
	return &NormalizationsGet0Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewNormalizationsGet0ParamsWithTimeout creates a new NormalizationsGet0Params object
// with the ability to set a timeout on a request.
func NewNormalizationsGet0ParamsWithTimeout(timeout time.Duration) *NormalizationsGet0Params {
	return &NormalizationsGet0Params{
		timeout: timeout,
	}
}

// NewNormalizationsGet0ParamsWithContext creates a new NormalizationsGet0Params object
// with the ability to set a context for a request.
func NewNormalizationsGet0ParamsWithContext(ctx context.Context) *NormalizationsGet0Params {
	return &NormalizationsGet0Params{
		Context: ctx,
	}
}

// NewNormalizationsGet0ParamsWithHTTPClient creates a new NormalizationsGet0Params object
// with the ability to set a custom HTTPClient for a request.
func NewNormalizationsGet0ParamsWithHTTPClient(client *http.Client) *NormalizationsGet0Params {
	return &NormalizationsGet0Params{
		HTTPClient: client,
	}
}

/* NormalizationsGet0Params contains all the parameters to send to the API endpoint
   for the normalizations get 0 operation.

   Typically these are written to a http.Request.
*/
type NormalizationsGet0Params struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	/* Key.

	   The key of the normalization set.
	*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the normalizations get 0 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsGet0Params) WithDefaults() *NormalizationsGet0Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the normalizations get 0 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsGet0Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the normalizations get 0 params
func (o *NormalizationsGet0Params) WithTimeout(timeout time.Duration) *NormalizationsGet0Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the normalizations get 0 params
func (o *NormalizationsGet0Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the normalizations get 0 params
func (o *NormalizationsGet0Params) WithContext(ctx context.Context) *NormalizationsGet0Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the normalizations get 0 params
func (o *NormalizationsGet0Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the normalizations get 0 params
func (o *NormalizationsGet0Params) WithHTTPClient(client *http.Client) *NormalizationsGet0Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the normalizations get 0 params
func (o *NormalizationsGet0Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the normalizations get 0 params
func (o *NormalizationsGet0Params) WithSovrenAccountID(sovrenAccountID string) *NormalizationsGet0Params {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the normalizations get 0 params
func (o *NormalizationsGet0Params) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the normalizations get 0 params
func (o *NormalizationsGet0Params) WithSovrenServiceKey(sovrenServiceKey string) *NormalizationsGet0Params {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the normalizations get 0 params
func (o *NormalizationsGet0Params) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithKey adds the key to the normalizations get 0 params
func (o *NormalizationsGet0Params) WithKey(key string) *NormalizationsGet0Params {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the normalizations get 0 params
func (o *NormalizationsGet0Params) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *NormalizationsGet0Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
