// Code generated by go-swagger; DO NOT EDIT.

package normalizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNormalizationsGetParams creates a new NormalizationsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNormalizationsGetParams() *NormalizationsGetParams {
	return &NormalizationsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNormalizationsGetParamsWithTimeout creates a new NormalizationsGetParams object
// with the ability to set a timeout on a request.
func NewNormalizationsGetParamsWithTimeout(timeout time.Duration) *NormalizationsGetParams {
	return &NormalizationsGetParams{
		timeout: timeout,
	}
}

// NewNormalizationsGetParamsWithContext creates a new NormalizationsGetParams object
// with the ability to set a context for a request.
func NewNormalizationsGetParamsWithContext(ctx context.Context) *NormalizationsGetParams {
	return &NormalizationsGetParams{
		Context: ctx,
	}
}

// NewNormalizationsGetParamsWithHTTPClient creates a new NormalizationsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewNormalizationsGetParamsWithHTTPClient(client *http.Client) *NormalizationsGetParams {
	return &NormalizationsGetParams{
		HTTPClient: client,
	}
}

/* NormalizationsGetParams contains all the parameters to send to the API endpoint
   for the normalizations get operation.

   Typically these are written to a http.Request.
*/
type NormalizationsGetParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the normalizations get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsGetParams) WithDefaults() *NormalizationsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the normalizations get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NormalizationsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the normalizations get params
func (o *NormalizationsGetParams) WithTimeout(timeout time.Duration) *NormalizationsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the normalizations get params
func (o *NormalizationsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the normalizations get params
func (o *NormalizationsGetParams) WithContext(ctx context.Context) *NormalizationsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the normalizations get params
func (o *NormalizationsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the normalizations get params
func (o *NormalizationsGetParams) WithHTTPClient(client *http.Client) *NormalizationsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the normalizations get params
func (o *NormalizationsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the normalizations get params
func (o *NormalizationsGetParams) WithSovrenAccountID(sovrenAccountID string) *NormalizationsGetParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the normalizations get params
func (o *NormalizationsGetParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the normalizations get params
func (o *NormalizationsGetParams) WithSovrenServiceKey(sovrenServiceKey string) *NormalizationsGetParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the normalizations get params
func (o *NormalizationsGetParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WriteToRequest writes these params to a swagger request
func (o *NormalizationsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
