// Code generated by go-swagger; DO NOT EDIT.

package searcher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// SearcherPostReader is a Reader for the SearcherPost structure.
type SearcherPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearcherPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearcherPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearcherPostOK creates a SearcherPostOK with default headers values
func NewSearcherPostOK() *SearcherPostOK {
	return &SearcherPostOK{}
}

/* SearcherPostOK describes a response with status code 200, with default header values.

OK
*/
type SearcherPostOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10V10SearchResponseSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *SearcherPostOK) Error() string {
	return fmt.Sprintf("[POST /v10/searcher][%d] searcherPostOK  %+v", 200, o.Payload)
}
func (o *SearcherPostOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10V10SearchResponseSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *SearcherPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10V10SearchResponseSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
