// Code generated by go-swagger; DO NOT EDIT.

package geocode_and_index

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// GeocodeAndIndexGeocodeAndIndexJobReader is a Reader for the GeocodeAndIndexGeocodeAndIndexJob structure.
type GeocodeAndIndexGeocodeAndIndexJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GeocodeAndIndexGeocodeAndIndexJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGeocodeAndIndexGeocodeAndIndexJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGeocodeAndIndexGeocodeAndIndexJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGeocodeAndIndexGeocodeAndIndexJobOK creates a GeocodeAndIndexGeocodeAndIndexJobOK with default headers values
func NewGeocodeAndIndexGeocodeAndIndexJobOK() *GeocodeAndIndexGeocodeAndIndexJobOK {
	return &GeocodeAndIndexGeocodeAndIndexJobOK{}
}

/* GeocodeAndIndexGeocodeAndIndexJobOK describes a response with status code 200, with default header values.

OK
*/
type GeocodeAndIndexGeocodeAndIndexJobOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10GeocodeAndIndexJobResponseSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *GeocodeAndIndexGeocodeAndIndexJobOK) Error() string {
	return fmt.Sprintf("[POST /v10/geocodeAndIndex/joborder][%d] geocodeAndIndexGeocodeAndIndexJobOK  %+v", 200, o.Payload)
}
func (o *GeocodeAndIndexGeocodeAndIndexJobOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10GeocodeAndIndexJobResponseSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *GeocodeAndIndexGeocodeAndIndexJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10GeocodeAndIndexJobResponseSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGeocodeAndIndexGeocodeAndIndexJobUnauthorized creates a GeocodeAndIndexGeocodeAndIndexJobUnauthorized with default headers values
func NewGeocodeAndIndexGeocodeAndIndexJobUnauthorized() *GeocodeAndIndexGeocodeAndIndexJobUnauthorized {
	return &GeocodeAndIndexGeocodeAndIndexJobUnauthorized{}
}

/* GeocodeAndIndexGeocodeAndIndexJobUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type GeocodeAndIndexGeocodeAndIndexJobUnauthorized struct {
	Payload string
}

func (o *GeocodeAndIndexGeocodeAndIndexJobUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v10/geocodeAndIndex/joborder][%d] geocodeAndIndexGeocodeAndIndexJobUnauthorized  %+v", 401, o.Payload)
}
func (o *GeocodeAndIndexGeocodeAndIndexJobUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GeocodeAndIndexGeocodeAndIndexJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
