// Code generated by go-swagger; DO NOT EDIT.

package scorer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new scorer API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for scorer API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ScorerBimetricScoreJob(params *ScorerBimetricScoreJobParams, opts ...ClientOption) (*ScorerBimetricScoreJobOK, error)

	ScorerBimetricScoreResume(params *ScorerBimetricScoreResumeParams, opts ...ClientOption) (*ScorerBimetricScoreResumeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ScorerBimetricScoreJob bimetrics score a job against a set of target resumes and jobs
*/
func (a *Client) ScorerBimetricScoreJob(params *ScorerBimetricScoreJobParams, opts ...ClientOption) (*ScorerBimetricScoreJobOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewScorerBimetricScoreJobParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Scorer_BimetricScoreJob",
		Method:             "POST",
		PathPattern:        "/v10/scorer/bimetric/joborder",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ScorerBimetricScoreJobReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ScorerBimetricScoreJobOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Scorer_BimetricScoreJob: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ScorerBimetricScoreResume bimetrics score a resume against a set of target resumes and jobs
*/
func (a *Client) ScorerBimetricScoreResume(params *ScorerBimetricScoreResumeParams, opts ...ClientOption) (*ScorerBimetricScoreResumeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewScorerBimetricScoreResumeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Scorer_BimetricScoreResume",
		Method:             "POST",
		PathPattern:        "/v10/scorer/bimetric/resume",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ScorerBimetricScoreResumeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ScorerBimetricScoreResumeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Scorer_BimetricScoreResume: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
