// Code generated by go-swagger; DO NOT EDIT.

package scorer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewScorerBimetricScoreResumeParams creates a new ScorerBimetricScoreResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewScorerBimetricScoreResumeParams() *ScorerBimetricScoreResumeParams {
	return &ScorerBimetricScoreResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewScorerBimetricScoreResumeParamsWithTimeout creates a new ScorerBimetricScoreResumeParams object
// with the ability to set a timeout on a request.
func NewScorerBimetricScoreResumeParamsWithTimeout(timeout time.Duration) *ScorerBimetricScoreResumeParams {
	return &ScorerBimetricScoreResumeParams{
		timeout: timeout,
	}
}

// NewScorerBimetricScoreResumeParamsWithContext creates a new ScorerBimetricScoreResumeParams object
// with the ability to set a context for a request.
func NewScorerBimetricScoreResumeParamsWithContext(ctx context.Context) *ScorerBimetricScoreResumeParams {
	return &ScorerBimetricScoreResumeParams{
		Context: ctx,
	}
}

// NewScorerBimetricScoreResumeParamsWithHTTPClient creates a new ScorerBimetricScoreResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewScorerBimetricScoreResumeParamsWithHTTPClient(client *http.Client) *ScorerBimetricScoreResumeParams {
	return &ScorerBimetricScoreResumeParams{
		HTTPClient: client,
	}
}

/* ScorerBimetricScoreResumeParams contains all the parameters to send to the API endpoint
   for the scorer bimetric score resume operation.

   Typically these are written to a http.Request.
*/
type ScorerBimetricScoreResumeParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// Request.
	Request *go_sovren_models.SovrenResumeBimetricMatchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scorer bimetric score resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScorerBimetricScoreResumeParams) WithDefaults() *ScorerBimetricScoreResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scorer bimetric score resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScorerBimetricScoreResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) WithTimeout(timeout time.Duration) *ScorerBimetricScoreResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) WithContext(ctx context.Context) *ScorerBimetricScoreResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) WithHTTPClient(client *http.Client) *ScorerBimetricScoreResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) WithSovrenAccountID(sovrenAccountID string) *ScorerBimetricScoreResumeParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) WithSovrenServiceKey(sovrenServiceKey string) *ScorerBimetricScoreResumeParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithRequest adds the request to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) WithRequest(request *go_sovren_models.SovrenResumeBimetricMatchRequest) *ScorerBimetricScoreResumeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the scorer bimetric score resume params
func (o *ScorerBimetricScoreResumeParams) SetRequest(request *go_sovren_models.SovrenResumeBimetricMatchRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *ScorerBimetricScoreResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
