// Code generated by go-swagger; DO NOT EDIT.

package scorer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// ScorerBimetricScoreJobReader is a Reader for the ScorerBimetricScoreJob structure.
type ScorerBimetricScoreJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScorerBimetricScoreJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewScorerBimetricScoreJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewScorerBimetricScoreJobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewScorerBimetricScoreJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewScorerBimetricScoreJobOK creates a ScorerBimetricScoreJobOK with default headers values
func NewScorerBimetricScoreJobOK() *ScorerBimetricScoreJobOK {
	return &ScorerBimetricScoreJobOK{}
}

/* ScorerBimetricScoreJobOK describes a response with status code 200, with default header values.

OK
*/
type ScorerBimetricScoreJobOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenV10BimetricMatchResponseSovrenCommonVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *ScorerBimetricScoreJobOK) Error() string {
	return fmt.Sprintf("[POST /v10/scorer/bimetric/joborder][%d] scorerBimetricScoreJobOK  %+v", 200, o.Payload)
}
func (o *ScorerBimetricScoreJobOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenV10BimetricMatchResponseSovrenCommonVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *ScorerBimetricScoreJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenV10BimetricMatchResponseSovrenCommonVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScorerBimetricScoreJobBadRequest creates a ScorerBimetricScoreJobBadRequest with default headers values
func NewScorerBimetricScoreJobBadRequest() *ScorerBimetricScoreJobBadRequest {
	return &ScorerBimetricScoreJobBadRequest{}
}

/* ScorerBimetricScoreJobBadRequest describes a response with status code 400, with default header values.

A message describing why the request couldn't be handled.
*/
type ScorerBimetricScoreJobBadRequest struct {
	Payload string
}

func (o *ScorerBimetricScoreJobBadRequest) Error() string {
	return fmt.Sprintf("[POST /v10/scorer/bimetric/joborder][%d] scorerBimetricScoreJobBadRequest  %+v", 400, o.Payload)
}
func (o *ScorerBimetricScoreJobBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ScorerBimetricScoreJobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScorerBimetricScoreJobUnauthorized creates a ScorerBimetricScoreJobUnauthorized with default headers values
func NewScorerBimetricScoreJobUnauthorized() *ScorerBimetricScoreJobUnauthorized {
	return &ScorerBimetricScoreJobUnauthorized{}
}

/* ScorerBimetricScoreJobUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type ScorerBimetricScoreJobUnauthorized struct {
	Payload string
}

func (o *ScorerBimetricScoreJobUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v10/scorer/bimetric/joborder][%d] scorerBimetricScoreJobUnauthorized  %+v", 401, o.Payload)
}
func (o *ScorerBimetricScoreJobUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *ScorerBimetricScoreJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
