// Code generated by go-swagger; DO NOT EDIT.

package geocoder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new geocoder API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for geocoder API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GeocoderGeocodeJob(params *GeocoderGeocodeJobParams, opts ...ClientOption) (*GeocoderGeocodeJobOK, error)

	GeocoderGeocodeResume(params *GeocoderGeocodeResumeParams, opts ...ClientOption) (*GeocoderGeocodeResumeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GeocoderGeocodeJob geocodes an already parsed v10 job order
*/
func (a *Client) GeocoderGeocodeJob(params *GeocoderGeocodeJobParams, opts ...ClientOption) (*GeocoderGeocodeJobOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGeocoderGeocodeJobParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Geocoder_GeocodeJob",
		Method:             "POST",
		PathPattern:        "/v10/geocoder/joborder",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GeocoderGeocodeJobReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GeocoderGeocodeJobOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Geocoder_GeocodeJob: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GeocoderGeocodeResume geocodes an already parsed v10 resume
*/
func (a *Client) GeocoderGeocodeResume(params *GeocoderGeocodeResumeParams, opts ...ClientOption) (*GeocoderGeocodeResumeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGeocoderGeocodeResumeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Geocoder_GeocodeResume",
		Method:             "POST",
		PathPattern:        "/v10/geocoder/resume",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GeocoderGeocodeResumeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GeocoderGeocodeResumeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Geocoder_GeocodeResume: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
