// Code generated by go-swagger; DO NOT EDIT.

package geocoder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewGeocoderGeocodeResumeParams creates a new GeocoderGeocodeResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGeocoderGeocodeResumeParams() *GeocoderGeocodeResumeParams {
	return &GeocoderGeocodeResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGeocoderGeocodeResumeParamsWithTimeout creates a new GeocoderGeocodeResumeParams object
// with the ability to set a timeout on a request.
func NewGeocoderGeocodeResumeParamsWithTimeout(timeout time.Duration) *GeocoderGeocodeResumeParams {
	return &GeocoderGeocodeResumeParams{
		timeout: timeout,
	}
}

// NewGeocoderGeocodeResumeParamsWithContext creates a new GeocoderGeocodeResumeParams object
// with the ability to set a context for a request.
func NewGeocoderGeocodeResumeParamsWithContext(ctx context.Context) *GeocoderGeocodeResumeParams {
	return &GeocoderGeocodeResumeParams{
		Context: ctx,
	}
}

// NewGeocoderGeocodeResumeParamsWithHTTPClient creates a new GeocoderGeocodeResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGeocoderGeocodeResumeParamsWithHTTPClient(client *http.Client) *GeocoderGeocodeResumeParams {
	return &GeocoderGeocodeResumeParams{
		HTTPClient: client,
	}
}

/* GeocoderGeocodeResumeParams contains all the parameters to send to the API endpoint
   for the geocoder geocode resume operation.

   Typically these are written to a http.Request.
*/
type GeocoderGeocodeResumeParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	/* RequestModel.

	   An object with a parsed resume and additional options.
	*/
	RequestModel *go_sovren_models.SovrenSaasDomainV10GeoCodeResumeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the geocoder geocode resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GeocoderGeocodeResumeParams) WithDefaults() *GeocoderGeocodeResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the geocoder geocode resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GeocoderGeocodeResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) WithTimeout(timeout time.Duration) *GeocoderGeocodeResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) WithContext(ctx context.Context) *GeocoderGeocodeResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) WithHTTPClient(client *http.Client) *GeocoderGeocodeResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) WithSovrenAccountID(sovrenAccountID string) *GeocoderGeocodeResumeParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) WithSovrenServiceKey(sovrenServiceKey string) *GeocoderGeocodeResumeParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithRequestModel adds the requestModel to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) WithRequestModel(requestModel *go_sovren_models.SovrenSaasDomainV10GeoCodeResumeRequest) *GeocoderGeocodeResumeParams {
	o.SetRequestModel(requestModel)
	return o
}

// SetRequestModel adds the requestModel to the geocoder geocode resume params
func (o *GeocoderGeocodeResumeParams) SetRequestModel(requestModel *go_sovren_models.SovrenSaasDomainV10GeoCodeResumeRequest) {
	o.RequestModel = requestModel
}

// WriteToRequest writes these params to a swagger request
func (o *GeocoderGeocodeResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}
	if o.RequestModel != nil {
		if err := r.SetBodyParam(o.RequestModel); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
