// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// SkillsPutReader is a Reader for the SkillsPut structure.
type SkillsPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SkillsPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSkillsPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSkillsPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSkillsPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSkillsPutOK creates a SkillsPutOK with default headers values
func NewSkillsPutOK() *SkillsPutOK {
	return &SkillsPutOK{}
}

/* SkillsPutOK describes a response with status code 200, with default header values.

A model describing the Skill PUT
*/
type SkillsPutOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *SkillsPutOK) Error() string {
	return fmt.Sprintf("[PUT /v10/skills/{key}][%d] skillsPutOK  %+v", 200, o.Payload)
}
func (o *SkillsPutOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *SkillsPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsPutBadRequest creates a SkillsPutBadRequest with default headers values
func NewSkillsPutBadRequest() *SkillsPutBadRequest {
	return &SkillsPutBadRequest{}
}

/* SkillsPutBadRequest describes a response with status code 400, with default header values.

A message describing why the message was in a bad state.
*/
type SkillsPutBadRequest struct {
	Payload string
}

func (o *SkillsPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v10/skills/{key}][%d] skillsPutBadRequest  %+v", 400, o.Payload)
}
func (o *SkillsPutBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SkillsPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsPutUnauthorized creates a SkillsPutUnauthorized with default headers values
func NewSkillsPutUnauthorized() *SkillsPutUnauthorized {
	return &SkillsPutUnauthorized{}
}

/* SkillsPutUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type SkillsPutUnauthorized struct {
	Payload string
}

func (o *SkillsPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v10/skills/{key}][%d] skillsPutUnauthorized  %+v", 401, o.Payload)
}
func (o *SkillsPutUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *SkillsPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
