// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewSkillsPutParams creates a new SkillsPutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSkillsPutParams() *SkillsPutParams {
	return &SkillsPutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSkillsPutParamsWithTimeout creates a new SkillsPutParams object
// with the ability to set a timeout on a request.
func NewSkillsPutParamsWithTimeout(timeout time.Duration) *SkillsPutParams {
	return &SkillsPutParams{
		timeout: timeout,
	}
}

// NewSkillsPutParamsWithContext creates a new SkillsPutParams object
// with the ability to set a context for a request.
func NewSkillsPutParamsWithContext(ctx context.Context) *SkillsPutParams {
	return &SkillsPutParams{
		Context: ctx,
	}
}

// NewSkillsPutParamsWithHTTPClient creates a new SkillsPutParams object
// with the ability to set a custom HTTPClient for a request.
func NewSkillsPutParamsWithHTTPClient(client *http.Client) *SkillsPutParams {
	return &SkillsPutParams{
		HTTPClient: client,
	}
}

/* SkillsPutParams contains all the parameters to send to the API endpoint
   for the skills put operation.

   Typically these are written to a http.Request.
*/
type SkillsPutParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	/* Key.

	   They key of the item to update
	*/
	Key string

	/* Request.

	   The UpdateSkillRequest object.
	*/
	Request *go_sovren_models.SovrenSaasDomainUpdateSkillRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the skills put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SkillsPutParams) WithDefaults() *SkillsPutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the skills put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SkillsPutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the skills put params
func (o *SkillsPutParams) WithTimeout(timeout time.Duration) *SkillsPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the skills put params
func (o *SkillsPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the skills put params
func (o *SkillsPutParams) WithContext(ctx context.Context) *SkillsPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the skills put params
func (o *SkillsPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the skills put params
func (o *SkillsPutParams) WithHTTPClient(client *http.Client) *SkillsPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the skills put params
func (o *SkillsPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the skills put params
func (o *SkillsPutParams) WithSovrenAccountID(sovrenAccountID string) *SkillsPutParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the skills put params
func (o *SkillsPutParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the skills put params
func (o *SkillsPutParams) WithSovrenServiceKey(sovrenServiceKey string) *SkillsPutParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the skills put params
func (o *SkillsPutParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithKey adds the key to the skills put params
func (o *SkillsPutParams) WithKey(key string) *SkillsPutParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the skills put params
func (o *SkillsPutParams) SetKey(key string) {
	o.Key = key
}

// WithRequest adds the request to the skills put params
func (o *SkillsPutParams) WithRequest(request *go_sovren_models.SovrenSaasDomainUpdateSkillRequest) *SkillsPutParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the skills put params
func (o *SkillsPutParams) SetRequest(request *go_sovren_models.SovrenSaasDomainUpdateSkillRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *SkillsPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
