// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// SkillsGetReader is a Reader for the SkillsGet structure.
type SkillsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SkillsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSkillsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSkillsGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSkillsGetOK creates a SkillsGetOK with default headers values
func NewSkillsGetOK() *SkillsGetOK {
	return &SkillsGetOK{}
}

/* SkillsGetOK describes a response with status code 200, with default header values.

A collection of available Skills
*/
type SkillsGetOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *SkillsGetOK) Error() string {
	return fmt.Sprintf("[GET /v10/skills][%d] skillsGetOK  %+v", 200, o.Payload)
}
func (o *SkillsGetOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *SkillsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsGetUnauthorized creates a SkillsGetUnauthorized with default headers values
func NewSkillsGetUnauthorized() *SkillsGetUnauthorized {
	return &SkillsGetUnauthorized{}
}

/* SkillsGetUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type SkillsGetUnauthorized struct {
	Payload string
}

func (o *SkillsGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v10/skills][%d] skillsGetUnauthorized  %+v", 401, o.Payload)
}
func (o *SkillsGetUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *SkillsGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
