// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSkillsDeleteParams creates a new SkillsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSkillsDeleteParams() *SkillsDeleteParams {
	return &SkillsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSkillsDeleteParamsWithTimeout creates a new SkillsDeleteParams object
// with the ability to set a timeout on a request.
func NewSkillsDeleteParamsWithTimeout(timeout time.Duration) *SkillsDeleteParams {
	return &SkillsDeleteParams{
		timeout: timeout,
	}
}

// NewSkillsDeleteParamsWithContext creates a new SkillsDeleteParams object
// with the ability to set a context for a request.
func NewSkillsDeleteParamsWithContext(ctx context.Context) *SkillsDeleteParams {
	return &SkillsDeleteParams{
		Context: ctx,
	}
}

// NewSkillsDeleteParamsWithHTTPClient creates a new SkillsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewSkillsDeleteParamsWithHTTPClient(client *http.Client) *SkillsDeleteParams {
	return &SkillsDeleteParams{
		HTTPClient: client,
	}
}

/* SkillsDeleteParams contains all the parameters to send to the API endpoint
   for the skills delete operation.

   Typically these are written to a http.Request.
*/
type SkillsDeleteParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// Key.
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the skills delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SkillsDeleteParams) WithDefaults() *SkillsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the skills delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SkillsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the skills delete params
func (o *SkillsDeleteParams) WithTimeout(timeout time.Duration) *SkillsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the skills delete params
func (o *SkillsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the skills delete params
func (o *SkillsDeleteParams) WithContext(ctx context.Context) *SkillsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the skills delete params
func (o *SkillsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the skills delete params
func (o *SkillsDeleteParams) WithHTTPClient(client *http.Client) *SkillsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the skills delete params
func (o *SkillsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the skills delete params
func (o *SkillsDeleteParams) WithSovrenAccountID(sovrenAccountID string) *SkillsDeleteParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the skills delete params
func (o *SkillsDeleteParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the skills delete params
func (o *SkillsDeleteParams) WithSovrenServiceKey(sovrenServiceKey string) *SkillsDeleteParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the skills delete params
func (o *SkillsDeleteParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithKey adds the key to the skills delete params
func (o *SkillsDeleteParams) WithKey(key string) *SkillsDeleteParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the skills delete params
func (o *SkillsDeleteParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *SkillsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
