// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// SkillsGet0Reader is a Reader for the SkillsGet0 structure.
type SkillsGet0Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SkillsGet0Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSkillsGet0OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSkillsGet0Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSkillsGet0OK creates a SkillsGet0OK with default headers values
func NewSkillsGet0OK() *SkillsGet0OK {
	return &SkillsGet0OK{}
}

/* SkillsGet0OK describes a response with status code 200, with default header values.

An array of strings. [0] is the Taxonomies. [1] is the Skills
*/
type SkillsGet0OK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SystemStringMscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089
}

func (o *SkillsGet0OK) Error() string {
	return fmt.Sprintf("[GET /v10/skills/{key}][%d] skillsGet0OK  %+v", 200, o.Payload)
}
func (o *SkillsGet0OK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SystemStringMscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089 {
	return o.Payload
}

func (o *SkillsGet0OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SystemStringMscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsGet0Unauthorized creates a SkillsGet0Unauthorized with default headers values
func NewSkillsGet0Unauthorized() *SkillsGet0Unauthorized {
	return &SkillsGet0Unauthorized{}
}

/* SkillsGet0Unauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type SkillsGet0Unauthorized struct {
	Payload string
}

func (o *SkillsGet0Unauthorized) Error() string {
	return fmt.Sprintf("[GET /v10/skills/{key}][%d] skillsGet0Unauthorized  %+v", 401, o.Payload)
}
func (o *SkillsGet0Unauthorized) GetPayload() string {
	return o.Payload
}

func (o *SkillsGet0Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
