// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// SkillsDeleteReader is a Reader for the SkillsDelete structure.
type SkillsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SkillsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSkillsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSkillsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSkillsDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSkillsDeleteOK creates a SkillsDeleteOK with default headers values
func NewSkillsDeleteOK() *SkillsDeleteOK {
	return &SkillsDeleteOK{}
}

/* SkillsDeleteOK describes a response with status code 200, with default header values.

An empty model
*/
type SkillsDeleteOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *SkillsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /v10/skills/{key}][%d] skillsDeleteOK  %+v", 200, o.Payload)
}
func (o *SkillsDeleteOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *SkillsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsDeleteBadRequest creates a SkillsDeleteBadRequest with default headers values
func NewSkillsDeleteBadRequest() *SkillsDeleteBadRequest {
	return &SkillsDeleteBadRequest{}
}

/* SkillsDeleteBadRequest describes a response with status code 400, with default header values.

A message describing why the message was in a bad state.
*/
type SkillsDeleteBadRequest struct {
	Payload string
}

func (o *SkillsDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v10/skills/{key}][%d] skillsDeleteBadRequest  %+v", 400, o.Payload)
}
func (o *SkillsDeleteBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SkillsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsDeleteUnauthorized creates a SkillsDeleteUnauthorized with default headers values
func NewSkillsDeleteUnauthorized() *SkillsDeleteUnauthorized {
	return &SkillsDeleteUnauthorized{}
}

/* SkillsDeleteUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type SkillsDeleteUnauthorized struct {
	Payload string
}

func (o *SkillsDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v10/skills/{key}][%d] skillsDeleteUnauthorized  %+v", 401, o.Payload)
}
func (o *SkillsDeleteUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *SkillsDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
