// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// SkillsPostReader is a Reader for the SkillsPost structure.
type SkillsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SkillsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSkillsPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSkillsPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSkillsPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSkillsPostOK creates a SkillsPostOK with default headers values
func NewSkillsPostOK() *SkillsPostOK {
	return &SkillsPostOK{}
}

/* SkillsPostOK describes a response with status code 200, with default header values.

A model of the Skills created
*/
type SkillsPostOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *SkillsPostOK) Error() string {
	return fmt.Sprintf("[POST /v10/skills][%d] skillsPostOK  %+v", 200, o.Payload)
}
func (o *SkillsPostOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *SkillsPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainSkillResponseModelSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsPostBadRequest creates a SkillsPostBadRequest with default headers values
func NewSkillsPostBadRequest() *SkillsPostBadRequest {
	return &SkillsPostBadRequest{}
}

/* SkillsPostBadRequest describes a response with status code 400, with default header values.

A message describing why the message was in a bad state.
*/
type SkillsPostBadRequest struct {
	Payload string
}

func (o *SkillsPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /v10/skills][%d] skillsPostBadRequest  %+v", 400, o.Payload)
}
func (o *SkillsPostBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SkillsPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSkillsPostUnauthorized creates a SkillsPostUnauthorized with default headers values
func NewSkillsPostUnauthorized() *SkillsPostUnauthorized {
	return &SkillsPostUnauthorized{}
}

/* SkillsPostUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type SkillsPostUnauthorized struct {
	Payload string
}

func (o *SkillsPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v10/skills][%d] skillsPostUnauthorized  %+v", 401, o.Payload)
}
func (o *SkillsPostUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *SkillsPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
