// Code generated by go-swagger; DO NOT EDIT.

package skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSkillsGetParams creates a new SkillsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSkillsGetParams() *SkillsGetParams {
	return &SkillsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSkillsGetParamsWithTimeout creates a new SkillsGetParams object
// with the ability to set a timeout on a request.
func NewSkillsGetParamsWithTimeout(timeout time.Duration) *SkillsGetParams {
	return &SkillsGetParams{
		timeout: timeout,
	}
}

// NewSkillsGetParamsWithContext creates a new SkillsGetParams object
// with the ability to set a context for a request.
func NewSkillsGetParamsWithContext(ctx context.Context) *SkillsGetParams {
	return &SkillsGetParams{
		Context: ctx,
	}
}

// NewSkillsGetParamsWithHTTPClient creates a new SkillsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewSkillsGetParamsWithHTTPClient(client *http.Client) *SkillsGetParams {
	return &SkillsGetParams{
		HTTPClient: client,
	}
}

/* SkillsGetParams contains all the parameters to send to the API endpoint
   for the skills get operation.

   Typically these are written to a http.Request.
*/
type SkillsGetParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the skills get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SkillsGetParams) WithDefaults() *SkillsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the skills get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SkillsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the skills get params
func (o *SkillsGetParams) WithTimeout(timeout time.Duration) *SkillsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the skills get params
func (o *SkillsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the skills get params
func (o *SkillsGetParams) WithContext(ctx context.Context) *SkillsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the skills get params
func (o *SkillsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the skills get params
func (o *SkillsGetParams) WithHTTPClient(client *http.Client) *SkillsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the skills get params
func (o *SkillsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the skills get params
func (o *SkillsGetParams) WithSovrenAccountID(sovrenAccountID string) *SkillsGetParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the skills get params
func (o *SkillsGetParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the skills get params
func (o *SkillsGetParams) WithSovrenServiceKey(sovrenServiceKey string) *SkillsGetParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the skills get params
func (o *SkillsGetParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WriteToRequest writes these params to a swagger request
func (o *SkillsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
