// Code generated by go-swagger; DO NOT EDIT.

package parser

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// ParserParseJobOrderReader is a Reader for the ParserParseJobOrder structure.
type ParserParseJobOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ParserParseJobOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewParserParseJobOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewParserParseJobOrderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewParserParseJobOrderUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewParserParseJobOrderOK creates a ParserParseJobOrderOK with default headers values
func NewParserParseJobOrderOK() *ParserParseJobOrderOK {
	return &ParserParseJobOrderOK{}
}

/* ParserParseJobOrderOK describes a response with status code 200, with default header values.

OK
*/
type ParserParseJobOrderOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10JobParsingTransactionSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *ParserParseJobOrderOK) Error() string {
	return fmt.Sprintf("[POST /v10/parser/joborder][%d] parserParseJobOrderOK  %+v", 200, o.Payload)
}
func (o *ParserParseJobOrderOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10JobParsingTransactionSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *ParserParseJobOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10JobParsingTransactionSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewParserParseJobOrderBadRequest creates a ParserParseJobOrderBadRequest with default headers values
func NewParserParseJobOrderBadRequest() *ParserParseJobOrderBadRequest {
	return &ParserParseJobOrderBadRequest{}
}

/* ParserParseJobOrderBadRequest describes a response with status code 400, with default header values.

A message describing why the message was in a bad state.
*/
type ParserParseJobOrderBadRequest struct {
	Payload string
}

func (o *ParserParseJobOrderBadRequest) Error() string {
	return fmt.Sprintf("[POST /v10/parser/joborder][%d] parserParseJobOrderBadRequest  %+v", 400, o.Payload)
}
func (o *ParserParseJobOrderBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ParserParseJobOrderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewParserParseJobOrderUnauthorized creates a ParserParseJobOrderUnauthorized with default headers values
func NewParserParseJobOrderUnauthorized() *ParserParseJobOrderUnauthorized {
	return &ParserParseJobOrderUnauthorized{}
}

/* ParserParseJobOrderUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type ParserParseJobOrderUnauthorized struct {
	Payload string
}

func (o *ParserParseJobOrderUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v10/parser/joborder][%d] parserParseJobOrderUnauthorized  %+v", 401, o.Payload)
}
func (o *ParserParseJobOrderUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *ParserParseJobOrderUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
