// Code generated by go-swagger; DO NOT EDIT.

package parser

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new parser API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for parser API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ParserParseJobOrder(params *ParserParseJobOrderParams, opts ...ClientOption) (*ParserParseJobOrderOK, error)

	ParserParseResume(params *ParserParseResumeParams, opts ...ClientOption) (*ParserParseResumeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ParserParseJobOrder parses a job order
*/
func (a *Client) ParserParseJobOrder(params *ParserParseJobOrderParams, opts ...ClientOption) (*ParserParseJobOrderOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewParserParseJobOrderParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Parser_ParseJobOrder",
		Method:             "POST",
		PathPattern:        "/v10/parser/joborder",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ParserParseJobOrderReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ParserParseJobOrderOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Parser_ParseJobOrder: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ParserParseResume parses a resume c v
*/
func (a *Client) ParserParseResume(params *ParserParseResumeParams, opts ...ClientOption) (*ParserParseResumeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewParserParseResumeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Parser_ParseResume",
		Method:             "POST",
		PathPattern:        "/v10/parser/resume",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ParserParseResumeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ParserParseResumeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Parser_ParseResume: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
