// Code generated by go-swagger; DO NOT EDIT.

package parser

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// ParserParseResumeReader is a Reader for the ParserParseResume structure.
type ParserParseResumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ParserParseResumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewParserParseResumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewParserParseResumeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewParserParseResumeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewParserParseResumeOK creates a ParserParseResumeOK with default headers values
func NewParserParseResumeOK() *ParserParseResumeOK {
	return &ParserParseResumeOK{}
}

/* ParserParseResumeOK describes a response with status code 200, with default header values.

OK
*/
type ParserParseResumeOK struct {
	Payload *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10ResumeParsingTransactionSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull
}

func (o *ParserParseResumeOK) Error() string {
	return fmt.Sprintf("[POST /v10/parser/resume][%d] parserParseResumeOK  %+v", 200, o.Payload)
}
func (o *ParserParseResumeOK) GetPayload() *go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10ResumeParsingTransactionSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull {
	return o.Payload
}

func (o *ParserParseResumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(go_sovren_models.SovrenSaasDomainV10ResponseModel1SovrenSaasDomainV10ResumeParsingTransactionSovrenSaasDomainVersion9520CultureNeutralPublicKeyTokenNull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewParserParseResumeBadRequest creates a ParserParseResumeBadRequest with default headers values
func NewParserParseResumeBadRequest() *ParserParseResumeBadRequest {
	return &ParserParseResumeBadRequest{}
}

/* ParserParseResumeBadRequest describes a response with status code 400, with default header values.

A message describing why the message was in a bad state.
*/
type ParserParseResumeBadRequest struct {
	Payload string
}

func (o *ParserParseResumeBadRequest) Error() string {
	return fmt.Sprintf("[POST /v10/parser/resume][%d] parserParseResumeBadRequest  %+v", 400, o.Payload)
}
func (o *ParserParseResumeBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ParserParseResumeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewParserParseResumeUnauthorized creates a ParserParseResumeUnauthorized with default headers values
func NewParserParseResumeUnauthorized() *ParserParseResumeUnauthorized {
	return &ParserParseResumeUnauthorized{}
}

/* ParserParseResumeUnauthorized describes a response with status code 401, with default header values.

A message describing why the message was unauthorized.
*/
type ParserParseResumeUnauthorized struct {
	Payload string
}

func (o *ParserParseResumeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v10/parser/resume][%d] parserParseResumeUnauthorized  %+v", 401, o.Payload)
}
func (o *ParserParseResumeUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *ParserParseResumeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
