// Code generated by go-swagger; DO NOT EDIT.

package parser

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewParserParseResumeParams creates a new ParserParseResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewParserParseResumeParams() *ParserParseResumeParams {
	return &ParserParseResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewParserParseResumeParamsWithTimeout creates a new ParserParseResumeParams object
// with the ability to set a timeout on a request.
func NewParserParseResumeParamsWithTimeout(timeout time.Duration) *ParserParseResumeParams {
	return &ParserParseResumeParams{
		timeout: timeout,
	}
}

// NewParserParseResumeParamsWithContext creates a new ParserParseResumeParams object
// with the ability to set a context for a request.
func NewParserParseResumeParamsWithContext(ctx context.Context) *ParserParseResumeParams {
	return &ParserParseResumeParams{
		Context: ctx,
	}
}

// NewParserParseResumeParamsWithHTTPClient creates a new ParserParseResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewParserParseResumeParamsWithHTTPClient(client *http.Client) *ParserParseResumeParams {
	return &ParserParseResumeParams{
		HTTPClient: client,
	}
}

/* ParserParseResumeParams contains all the parameters to send to the API endpoint
   for the parser parse resume operation.

   Typically these are written to a http.Request.
*/
type ParserParseResumeParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	/* Request.

	   The ParseResumeRequest object.
	*/
	Request *go_sovren_models.SovrenSaasServicesRestDomainV10ParseResumeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the parser parse resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ParserParseResumeParams) WithDefaults() *ParserParseResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the parser parse resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ParserParseResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the parser parse resume params
func (o *ParserParseResumeParams) WithTimeout(timeout time.Duration) *ParserParseResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the parser parse resume params
func (o *ParserParseResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the parser parse resume params
func (o *ParserParseResumeParams) WithContext(ctx context.Context) *ParserParseResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the parser parse resume params
func (o *ParserParseResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the parser parse resume params
func (o *ParserParseResumeParams) WithHTTPClient(client *http.Client) *ParserParseResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the parser parse resume params
func (o *ParserParseResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the parser parse resume params
func (o *ParserParseResumeParams) WithSovrenAccountID(sovrenAccountID string) *ParserParseResumeParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the parser parse resume params
func (o *ParserParseResumeParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the parser parse resume params
func (o *ParserParseResumeParams) WithSovrenServiceKey(sovrenServiceKey string) *ParserParseResumeParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the parser parse resume params
func (o *ParserParseResumeParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithRequest adds the request to the parser parse resume params
func (o *ParserParseResumeParams) WithRequest(request *go_sovren_models.SovrenSaasServicesRestDomainV10ParseResumeRequest) *ParserParseResumeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the parser parse resume params
func (o *ParserParseResumeParams) SetRequest(request *go_sovren_models.SovrenSaasServicesRestDomainV10ParseResumeRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *ParserParseResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
