// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewDocumentPostResumeParams creates a new DocumentPostResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDocumentPostResumeParams() *DocumentPostResumeParams {
	return &DocumentPostResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDocumentPostResumeParamsWithTimeout creates a new DocumentPostResumeParams object
// with the ability to set a timeout on a request.
func NewDocumentPostResumeParamsWithTimeout(timeout time.Duration) *DocumentPostResumeParams {
	return &DocumentPostResumeParams{
		timeout: timeout,
	}
}

// NewDocumentPostResumeParamsWithContext creates a new DocumentPostResumeParams object
// with the ability to set a context for a request.
func NewDocumentPostResumeParamsWithContext(ctx context.Context) *DocumentPostResumeParams {
	return &DocumentPostResumeParams{
		Context: ctx,
	}
}

// NewDocumentPostResumeParamsWithHTTPClient creates a new DocumentPostResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewDocumentPostResumeParamsWithHTTPClient(client *http.Client) *DocumentPostResumeParams {
	return &DocumentPostResumeParams{
		HTTPClient: client,
	}
}

/* DocumentPostResumeParams contains all the parameters to send to the API endpoint
   for the document post resume operation.

   Typically these are written to a http.Request.
*/
type DocumentPostResumeParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// DocumentID.
	DocumentID string

	// IndexID.
	IndexID string

	// Request.
	Request *go_sovren_models.SovrenSaasDomainV10AddResumeToIndexRequestModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the document post resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentPostResumeParams) WithDefaults() *DocumentPostResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the document post resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentPostResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the document post resume params
func (o *DocumentPostResumeParams) WithTimeout(timeout time.Duration) *DocumentPostResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the document post resume params
func (o *DocumentPostResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the document post resume params
func (o *DocumentPostResumeParams) WithContext(ctx context.Context) *DocumentPostResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the document post resume params
func (o *DocumentPostResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the document post resume params
func (o *DocumentPostResumeParams) WithHTTPClient(client *http.Client) *DocumentPostResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the document post resume params
func (o *DocumentPostResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the document post resume params
func (o *DocumentPostResumeParams) WithSovrenAccountID(sovrenAccountID string) *DocumentPostResumeParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the document post resume params
func (o *DocumentPostResumeParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the document post resume params
func (o *DocumentPostResumeParams) WithSovrenServiceKey(sovrenServiceKey string) *DocumentPostResumeParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the document post resume params
func (o *DocumentPostResumeParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithDocumentID adds the documentID to the document post resume params
func (o *DocumentPostResumeParams) WithDocumentID(documentID string) *DocumentPostResumeParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the document post resume params
func (o *DocumentPostResumeParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WithIndexID adds the indexID to the document post resume params
func (o *DocumentPostResumeParams) WithIndexID(indexID string) *DocumentPostResumeParams {
	o.SetIndexID(indexID)
	return o
}

// SetIndexID adds the indexId to the document post resume params
func (o *DocumentPostResumeParams) SetIndexID(indexID string) {
	o.IndexID = indexID
}

// WithRequest adds the request to the document post resume params
func (o *DocumentPostResumeParams) WithRequest(request *go_sovren_models.SovrenSaasDomainV10AddResumeToIndexRequestModel) *DocumentPostResumeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the document post resume params
func (o *DocumentPostResumeParams) SetRequest(request *go_sovren_models.SovrenSaasDomainV10AddResumeToIndexRequestModel) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *DocumentPostResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param documentId
	if err := r.SetPathParam("documentId", o.DocumentID); err != nil {
		return err
	}

	// path param indexId
	if err := r.SetPathParam("indexId", o.IndexID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
