// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewDocumentPatchJobOrderParams creates a new DocumentPatchJobOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDocumentPatchJobOrderParams() *DocumentPatchJobOrderParams {
	return &DocumentPatchJobOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDocumentPatchJobOrderParamsWithTimeout creates a new DocumentPatchJobOrderParams object
// with the ability to set a timeout on a request.
func NewDocumentPatchJobOrderParamsWithTimeout(timeout time.Duration) *DocumentPatchJobOrderParams {
	return &DocumentPatchJobOrderParams{
		timeout: timeout,
	}
}

// NewDocumentPatchJobOrderParamsWithContext creates a new DocumentPatchJobOrderParams object
// with the ability to set a context for a request.
func NewDocumentPatchJobOrderParamsWithContext(ctx context.Context) *DocumentPatchJobOrderParams {
	return &DocumentPatchJobOrderParams{
		Context: ctx,
	}
}

// NewDocumentPatchJobOrderParamsWithHTTPClient creates a new DocumentPatchJobOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewDocumentPatchJobOrderParamsWithHTTPClient(client *http.Client) *DocumentPatchJobOrderParams {
	return &DocumentPatchJobOrderParams{
		HTTPClient: client,
	}
}

/* DocumentPatchJobOrderParams contains all the parameters to send to the API endpoint
   for the document patch job order operation.

   Typically these are written to a http.Request.
*/
type DocumentPatchJobOrderParams struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// DocumentID.
	DocumentID string

	// IndexID.
	IndexID string

	// Request.
	Request *go_sovren_models.SovrenV10UpdateDocumentCustomValuesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the document patch job order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentPatchJobOrderParams) WithDefaults() *DocumentPatchJobOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the document patch job order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentPatchJobOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithTimeout(timeout time.Duration) *DocumentPatchJobOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithContext(ctx context.Context) *DocumentPatchJobOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithHTTPClient(client *http.Client) *DocumentPatchJobOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithSovrenAccountID(sovrenAccountID string) *DocumentPatchJobOrderParams {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithSovrenServiceKey(sovrenServiceKey string) *DocumentPatchJobOrderParams {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithDocumentID adds the documentID to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithDocumentID(documentID string) *DocumentPatchJobOrderParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WithIndexID adds the indexID to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithIndexID(indexID string) *DocumentPatchJobOrderParams {
	o.SetIndexID(indexID)
	return o
}

// SetIndexID adds the indexId to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetIndexID(indexID string) {
	o.IndexID = indexID
}

// WithRequest adds the request to the document patch job order params
func (o *DocumentPatchJobOrderParams) WithRequest(request *go_sovren_models.SovrenV10UpdateDocumentCustomValuesRequest) *DocumentPatchJobOrderParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the document patch job order params
func (o *DocumentPatchJobOrderParams) SetRequest(request *go_sovren_models.SovrenV10UpdateDocumentCustomValuesRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *DocumentPatchJobOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param documentId
	if err := r.SetPathParam("documentId", o.DocumentID); err != nil {
		return err
	}

	// path param indexId
	if err := r.SetPathParam("indexId", o.IndexID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
