// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DocumentHeadReader is a Reader for the DocumentHead structure.
type DocumentHeadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DocumentHeadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDocumentHeadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDocumentHeadOK creates a DocumentHeadOK with default headers values
func NewDocumentHeadOK() *DocumentHeadOK {
	return &DocumentHeadOK{}
}

/* DocumentHeadOK describes a response with status code 200, with default header values.

OK
*/
type DocumentHeadOK struct {
}

func (o *DocumentHeadOK) Error() string {
	return fmt.Sprintf("[HEAD /v10/index/{indexId}/documents/{documentId}][%d] documentHeadOK ", 200)
}

func (o *DocumentHeadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
