// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/teamjobot/go_sovren_models"
)

// NewDocumentDelete0Params creates a new DocumentDelete0Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDocumentDelete0Params() *DocumentDelete0Params {
	return &DocumentDelete0Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewDocumentDelete0ParamsWithTimeout creates a new DocumentDelete0Params object
// with the ability to set a timeout on a request.
func NewDocumentDelete0ParamsWithTimeout(timeout time.Duration) *DocumentDelete0Params {
	return &DocumentDelete0Params{
		timeout: timeout,
	}
}

// NewDocumentDelete0ParamsWithContext creates a new DocumentDelete0Params object
// with the ability to set a context for a request.
func NewDocumentDelete0ParamsWithContext(ctx context.Context) *DocumentDelete0Params {
	return &DocumentDelete0Params{
		Context: ctx,
	}
}

// NewDocumentDelete0ParamsWithHTTPClient creates a new DocumentDelete0Params object
// with the ability to set a custom HTTPClient for a request.
func NewDocumentDelete0ParamsWithHTTPClient(client *http.Client) *DocumentDelete0Params {
	return &DocumentDelete0Params{
		HTTPClient: client,
	}
}

/* DocumentDelete0Params contains all the parameters to send to the API endpoint
   for the document delete 0 operation.

   Typically these are written to a http.Request.
*/
type DocumentDelete0Params struct {

	/* SovrenAccountID.

	   Provided Account Id
	*/
	SovrenAccountID string

	/* SovrenServiceKey.

	   Provided Service Key
	*/
	SovrenServiceKey string

	// IndexID.
	IndexID string

	// RequestModel.
	RequestModel *go_sovren_models.SovrenSaasDomainBulkDeleteRequestModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the document delete 0 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentDelete0Params) WithDefaults() *DocumentDelete0Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the document delete 0 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentDelete0Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the document delete 0 params
func (o *DocumentDelete0Params) WithTimeout(timeout time.Duration) *DocumentDelete0Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the document delete 0 params
func (o *DocumentDelete0Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the document delete 0 params
func (o *DocumentDelete0Params) WithContext(ctx context.Context) *DocumentDelete0Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the document delete 0 params
func (o *DocumentDelete0Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the document delete 0 params
func (o *DocumentDelete0Params) WithHTTPClient(client *http.Client) *DocumentDelete0Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the document delete 0 params
func (o *DocumentDelete0Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSovrenAccountID adds the sovrenAccountID to the document delete 0 params
func (o *DocumentDelete0Params) WithSovrenAccountID(sovrenAccountID string) *DocumentDelete0Params {
	o.SetSovrenAccountID(sovrenAccountID)
	return o
}

// SetSovrenAccountID adds the sovrenAccountId to the document delete 0 params
func (o *DocumentDelete0Params) SetSovrenAccountID(sovrenAccountID string) {
	o.SovrenAccountID = sovrenAccountID
}

// WithSovrenServiceKey adds the sovrenServiceKey to the document delete 0 params
func (o *DocumentDelete0Params) WithSovrenServiceKey(sovrenServiceKey string) *DocumentDelete0Params {
	o.SetSovrenServiceKey(sovrenServiceKey)
	return o
}

// SetSovrenServiceKey adds the sovrenServiceKey to the document delete 0 params
func (o *DocumentDelete0Params) SetSovrenServiceKey(sovrenServiceKey string) {
	o.SovrenServiceKey = sovrenServiceKey
}

// WithIndexID adds the indexID to the document delete 0 params
func (o *DocumentDelete0Params) WithIndexID(indexID string) *DocumentDelete0Params {
	o.SetIndexID(indexID)
	return o
}

// SetIndexID adds the indexId to the document delete 0 params
func (o *DocumentDelete0Params) SetIndexID(indexID string) {
	o.IndexID = indexID
}

// WithRequestModel adds the requestModel to the document delete 0 params
func (o *DocumentDelete0Params) WithRequestModel(requestModel *go_sovren_models.SovrenSaasDomainBulkDeleteRequestModel) *DocumentDelete0Params {
	o.SetRequestModel(requestModel)
	return o
}

// SetRequestModel adds the requestModel to the document delete 0 params
func (o *DocumentDelete0Params) SetRequestModel(requestModel *go_sovren_models.SovrenSaasDomainBulkDeleteRequestModel) {
	o.RequestModel = requestModel
}

// WriteToRequest writes these params to a swagger request
func (o *DocumentDelete0Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Sovren-AccountId
	if err := r.SetHeaderParam("Sovren-AccountId", o.SovrenAccountID); err != nil {
		return err
	}

	// header param Sovren-ServiceKey
	if err := r.SetHeaderParam("Sovren-ServiceKey", o.SovrenServiceKey); err != nil {
		return err
	}

	// path param indexId
	if err := r.SetPathParam("indexId", o.IndexID); err != nil {
		return err
	}
	if o.RequestModel != nil {
		if err := r.SetBodyParam(o.RequestModel); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
